[package]
name = "imgchest"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = { version = "1.17.0", default-features = false, features = ["std"] }
reqwest = { version = "0.11.14", features = [ "cookies" ], default-features = false }
scraper = { version = "0.14.0", default-features = false }
thiserror = "1.0.38"
tokio = "1.24.1"

# Optional
serde = { version = "1.0.152", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1.24.1", features = [ "macros" ] }

[features]
default = ["rustls-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
serde = ["dep:serde"]
