[package]
name = "imgchest"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = { version = "1.19.0", default-features = false, features = ["std"] }
reqwest = { version = "0.12.4", features = [ "cookies" ], default-features = false }
scraper = { version = "0.19.0", default-features = false }
thiserror = "1.0.61"
tokio = "1.38.0"

# Optional
serde = { version = "1.0.203", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1.38.0", features = [ "macros" ] }

[features]
default = ["rustls-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
serde = ["dep:serde"]
